---
- name: Add Security Rules
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ provider }}'
    rule_name: 'siduser111-Block amp_{{ item.detection_id }}'
    description: '{{ rule_desc }}'
    source_zone: '{{ source_zone }}'
    destination_zone: '{{ destination_zone }}'
    source_ip: ['{{ item.computer.external_ip }}', '{{ item.computer.network_addresses[0].ip }}']
    destination_ip: ['{{ destination_ip }}']
    category: ['{{ category }}']
    application: ['{{ application }}']
    service: ['{{ service }}']
    action: '{{ rule_action }}'
    location: '{{ location }}'
    log_start: '{{ log_start }}'
    log_end: '{{ log_end }}'
    state: '{{ state }}'
  loop: '{{ erd_data.data }}'
  register: result

#  paloaltonetworks.panos.panos_security_rule:
#    provider: '{{ provider }}'
#    rule_name: '{{ rule_name }}'
#    description: '{{ rule_desc }}'
#    source_zone: '{{ source_zone }}'
#    destination_zone: '{{ destination_zone }}'
#    source_ip: ['{{ source_ip }}']
#    destination_ip: ['{{ destination_ip }}']
#    category: ['{{ category }}']
#    application: ['{{ application }}']
#    service: ['{{ service }}']
#    action: '{{ rule_action }}'
#    location: '{{ location }}'
#    log_start: '{{ log_start }}'
#    log_end: '{{ log_end }}'
#    state: '{{ state }}'

